# The namesapce 
apiVersion: v1
kind: Namespace
metadata:
  name: gok8s-system
# the deployment and the POD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-depl
  namespace: gok8s-system
spec:
  selector:
    matchLabels:
      app: sales-api-pod
  template:
    metadata:
      labels:
        app: sales-api-pod
    spec:
      # base networking spec 
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      # pointing to the image we created
      containers:
      - name: sales-api-pod
        image: sales-api-image


